laban.gg-main/labanGG/labanGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('games/', include('games_list.urls', namespace="games_list")),
    path('tournaments/', include('tournaments_list.urls', namespace="tournaments_list")),
    path('admin/', admin.site.urls),
    path('', include("create_tournament.urls")),
    path('log_in/', include('log_in.urls', namespace="log_in")),
    path('register/', include('register.urls', namespace="register")),
    path('tournament<int:id>/player_applications_list/', include('player_applications_list.urls', namespace="player_applications_list")),
    path('my_tournaments_organizer/', include('my_tournaments_organizer.urls', namespace="my_tournaments_organizer")),
    path('', include('join_tournament.urls', namespace="join_tournament")),
    path('notifications_page/', include('notifications_page.urls', namespace="notifications_page")),
    path('profile/', include('player_profile.urls', namespace="player_profile")),
    path('tournament<int:id>/tournament_details/', include('tournament_details.urls', namespace="tournament_details")),
    path('my_tournaments_attendee/', include('my_tournaments_attendee.urls', namespace="my_tournaments_attendee")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laban.gg-main/labanGG/log_in/urls.py
from django.urls import path
from .views import log_in_view

urlpatterns = [
    path('', log_in_view, name='log_in_view'),
    ]
# This might be needed, depending on your Django version
app_name = "log_in"

laban.gg-main/labanGG/tournament_details/urls.py
from django.urls import path
from .views import tournament_details, brackets

urlpatterns = [
    path('', tournament_details, name='tournament_details'),
    path('brackets/', brackets, name='brackets'),
]

app_name = "tournament_details"

laban.gg-main/labanGG/tournament_details/models.py
from django.db import models
from create_tournament.models import Tournament
from join_tournament.models import TournamentPlayer


class Bracket(models.Model):
	tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
	classification = models.CharField(max_length=15)


class Matchup(models.Model):
	bracket = models.ForeignKey(Bracket, on_delete=models.CASCADE, related_name='matchups')
	matchNumber = models.IntegerField()
	status = models.CharField(max_length=10, default="Upcoming")
	resultConfirmed = models.BooleanField(default=False)


class PlayerInMatchup(models.Model):
	player = models.ForeignKey(TournamentPlayer, on_delete=models.CASCADE)
	matchup = models.ForeignKey(Matchup, on_delete=models.CASCADE)
	playerNumber = models.IntegerField()
	isWinner = models.BooleanField(null=True)
	score = models.IntegerField(default = -1)

	def __str__(self):
		return f"{self.player.ign} in {self.matchup.matchNumber} of {self.matchup.bracket.classification} Bracket"

laban.gg-main/labanGG/tournament_details/views.py
import random
from django.shortcuts import render, redirect
from create_tournament.models import Tournament
from register.models import Account
from join_tournament.models import TournamentPlayer
from .models import Bracket, Matchup, PlayerInMatchup

# function that will generate the initial matchups for the tournament
def generateMatchups(tournament):
    winnersBracket = Bracket(tournament=tournament, classification="Winners")
    winnersBracket.save()

    if tournament.format == "double_elimination":
        losersBracket = Bracket(tournament=tournament, classification="Losers")
        losersBracket.save()

    players = TournamentPlayer.objects.filter(tournament=tournament)
    players = list(players.filter(application_status="Accepted"))
    random.shuffle(players)

    # first round matchups
    for i in range(0, len(players)-1, 2):
        matchup = Matchup(bracket=winnersBracket, matchNumber=(i//2)+1, status="Ongoing")
        matchup.save()

        player1 = PlayerInMatchup(player=players[i], matchup=matchup, playerNumber=1)
        player1.save()

        player2 = PlayerInMatchup(player=players[i+1], matchup=matchup, playerNumber=2)
        player2.save()


# function that will update the brackets based on the result of a matchup
def updateBrackets(bracket, matchups, matchNumber, winner, loser, context):
    targetMatchup = ""

    if bracket.classification == "Winners":
        if matchNumber == 8 or (matchNumber == 7 and 'losersBracket' not in context):
            winner.ranking = 1
            loser.ranking = 2

            winner.save()
            loser.save()

            tournament = bracket.tournament
            tournament.status = "Ended"
            tournament.save()

        else:
            if matchups.filter(matchNumber=5+(matchNumber-1)//2):
                targetMatchup = matchups.get(matchNumber=5+(matchNumber-1)//2)
                targetMatchup.status = "Ongoing"
            else:
                targetMatchup = Matchup(bracket=bracket, matchNumber=5+(matchNumber-1)//2)

            targetMatchup.save()

            advancingPlayer = PlayerInMatchup(player=winner, matchup=targetMatchup, playerNumber=(matchNumber-1)%2+1)
            advancingPlayer.save()

            if 'losersBracket' not in context:
                if matchNumber < 5:
                    loser.ranking = 5
                elif matchNumber < 7:
                    loser.ranking = 3

                loser.save()

            else:
                losersMatchups = Matchup.objects.filter(bracket=context['losersBracket'])
                
                if matchNumber < 5:
                    if losersMatchups.filter(matchNumber=(matchNumber-1)//2+1):
                        targetMatchup = losersMatchups.get(matchNumber=(matchNumber-1)//2+1)
                        targetMatchup.status = "Ongoing"

                    else:
                        targetMatchup = Matchup(bracket=context['losersBracket'], matchNumber=(matchNumber-1)//2+1)

                    targetMatchup.save()

                    relegatedPlayer = PlayerInMatchup(player=loser, matchup=targetMatchup, playerNumber=(matchNumber-1)%2+1)
                    relegatedPlayer.save()

                elif matchNumber < 7:
                    if losersMatchups.filter(matchNumber=matchNumber//2+1):
                        targetMatchup = losersMatchups.get(matchNumber=matchNumber//2+1)
                        targetMatchup.status = "Ongoing"

                    else:
                        targetMatchup = Matchup(bracket=context['losersBracket'], matchNumber=matchNumber//2+1)

                    targetMatchup.save()

                    relegatedPlayer = PlayerInMatchup(player=loser, matchup=targetMatchup, playerNumber=(matchNumber-1)%2+1)
                    relegatedPlayer.save()

                elif matchNumber == 7:
                    if losersMatchups.filter(matchNumber=6):
                        targetMatchup = losersMatchups.get(matchNumber=6)
                        targetMatchup.status = "Ongoing"

                    else:
                        targetMatchup = Matchup(bracket=context['losersBracket'], matchNumber=6)

                    targetMatchup.save()

                    relegatedPlayer = PlayerInMatchup(player=loser, matchup=targetMatchup, playerNumber=1)
                    relegatedPlayer.save()

    else:
        if matchNumber < 4:
            if matchups.filter(matchNumber=matchNumber+2):
                targetMatchup = matchups.get(matchNumber=matchNumber+2)
                targetMatchup.status = "Ongoing"
            else:
                targetMatchup = Matchup(bracket=bracket, matchNumber=matchNumber+2)

            targetMatchup.save()

            if matchNumber < 3:
                advancingPlayer = PlayerInMatchup(player=winner, matchup=targetMatchup, playerNumber=matchNumber%2+1)
                loser.ranking = 7
            else:
                advancingPlayer = PlayerInMatchup(player=winner, matchup=targetMatchup, playerNumber=1)
                loser.ranking = 5

            advancingPlayer.save()
            loser.save()

        elif matchNumber < 6:
            if matchups.filter(matchNumber=matchNumber+1):
                targetMatchup = matchups.get(matchNumber=matchNumber+1)
                targetMatchup.status = "Ongoing"
            else:
                targetMatchup = Matchup(bracket=bracket, matchNumber=matchNumber+1)

            targetMatchup.save()

            advancingPlayer = PlayerInMatchup(player=winner, matchup=targetMatchup, playerNumber=2)
            advancingPlayer.save()

            loser.ranking = 9 - matchNumber
            loser.save()

        elif matchNumber == 6:
            winnersMatchups = Matchup.objects.filter(bracket=context['winnersBracket'])

            if winnersMatchups.filter(matchNumber=8):
                targetMatchup = winnersMatchups.get(matchNumber=8)
                targetMatchup.status = "Ongoing"
            else:
                targetMatchup = Matchup(bracket=context['winnersBracket'], matchNumber=8)

            targetMatchup.save()

            advancingPlayer = PlayerInMatchup(player=winner, matchup=targetMatchup, playerNumber=2)
            advancingPlayer.save()

            loser.ranking = 3
            loser.save()


# Create your views here.
def tournament_details(request, id):
    context = {}

    tournament = Tournament.objects.get(id=id)
    
    user = request.user
    context['user'] = user
    context['base_template'] = 'base_organizer.html' if user.isOrganizer else 'base_attendee.html'

    if request.POST.get('updateTourneyStatus'):
        if tournament.status == "Upcoming":
            tournament.status = "Pending"
        elif tournament.status == "Pending":
            tournament.status = "Ongoing"
            generateMatchups(tournament)

        elif tournament.status == "Paused":
            tournament.status = "Ongoing"
        elif tournament.status == "Ongoing":
            tournament.status = "Paused"

        tournament.save()

    elif request.POST.get('notStartingYet'):
        tournament.status = "Upcoming"
        tournament.save()

    elif request.POST.get('goToJoinTourney'):
        return redirect(f'/tournament{id}/jointournament/')

    context['tournament'] = tournament

    return render(request, 'tournament_details.html', context)


def brackets(request, id):
    context = {}

    tournament = Tournament.objects.get(id=id)
    user = request.user

    context['tournament'] = tournament
    context['base_template'] = 'base_organizer.html' if user.isOrganizer else 'base_attendee.html'

    brackets = Bracket.objects.filter(tournament=tournament)

    if brackets.count() >= 1:
        winnersBracket = brackets.get(classification="Winners")
        context['winnersBracket'] = winnersBracket
        
        if brackets.count() == 2:
            losersBracket = brackets.get(classification="Losers")
            context['losersBracket'] = losersBracket

    if request.method == "POST":
        for bracket in brackets:
            matchupFound = False

            matchups = Matchup.objects.filter(bracket=bracket)
            ongoingMatchups = matchups.filter(status="Ongoing")

            for matchup in ongoingMatchups:
                matchNumber = matchup.matchNumber
                prefix = ""

                if request.POST.get(f"reportLMatch{matchNumber}Score"):
                    if bracket.classification == "Winners":
                        break
                    else:
                        prefix = "L"
                        matchupFound = True

                elif request.POST.get(f"reportWMatch{matchNumber}Score"):
                    if bracket.classification == "Losers":
                        break
                    else:
                        prefix = "W"
                        matchupFound = True

                if matchupFound:
                    p1score = int(request.POST.get(f"{prefix}m{matchNumber}p1score"))
                    p2score = int(request.POST.get(f"{prefix}m{matchNumber}p2score"))

                    players = PlayerInMatchup.objects.filter(matchup=matchup)
                    player1 = players.get(playerNumber=1)
                    player2 = players.get(playerNumber=2)

                    winner = ""
                    loser = ""

                    if player1.player.account == user or player2.player.account == user:
                        if player1.score == -1 and player2.score == -1:
                            player1.score = p1score
                            player2.score = p2score

                            context['message'] = f"""Successfully reported score ({p1score} - {p2score}) for Match {matchNumber} in {bracket.classification} Bracket!\n
                                                    Waiting for other player to report to confirm the score..."""

                        elif player1.score == p1score and player2.score == p2score:

laban.gg-main/labanGG/tournament_details/templates/brackets.html
{% extends base_template %}
{% load static %}

{% block title %}Tournament Brackets{% endblock %}

{% block content %}
	<head>
        <meta charset="UTF-8">
        <title>Tournament Brackets</title>
        <style>
        	body {
                background-color: #4D24AC;
                color: white;
                margin-left: 125px;
            }
            .pink-button {
                background-color: #F6247B;
                color: white;
                border: none;
                padding: 10px 10px;
                border-radius: 30px;
                cursor: pointer;
                margin-top: 20px;
                width: 200px;
                text-align: center;
            }
            .bracket {
                display: grid;
                grid-template-columns: 250px 250px 250px 250px;
                justify-content: left;
                align-items: left;
            }
            .round {
            	width: 250px;
            }
            .player-box {
            	background-color: black;
            	width: 120px;
                padding: 10px;
                color: white;
            }
            .player {
            	background-color: #9400D3;
                width: 120px;
                display: grid;
                grid-template-columns: 95px 15px;
                justify-content: center;
                align-items: center;
            }
            .bracket input {
                background-color: white;
                border: none;
                margin-bottom: 1px;
            	width: 15px;
            	color: black;
            	text-align: center;
            }
            .bracket button {
                background-color: #F6247B;
                color: white;
                border: none;
                padding: 10px 10px;
                border-radius: 50px;
                cursor: pointer;
                margin-top: 10px;
                margin-bottom: 20px;
            }
        </style>
    </head>

    <body>
    	<div class="pink-button"><a href="/tournament{{tournament.id}}/tournament_details/">Back to Tournament Details</a></div>
    	<form method="POST">
    		{% csrf_token %}

    		<h3>{{ message }}</h3>

	    	{% if winnersBracket %}
			    <h2>Winner's Bracket</h2>
	    		<div class="bracket">
			    	{% for matchup in winnersBracket.matchups.all|dictsort:"matchNumber" %}
			    		{% if matchup.matchNumber == 1 or matchup.matchNumber == 5 or matchup.matchNumber >= 7 %}
			    			<div class="round">
			    		{% endif %}

		    			{% if matchup.matchNumber >= 5 %}
		    				<br><br><br><br>
		    			{% endif %}

		    			{% if matchup.matchNumber >= 6 %}
		    				<br><br><br><br><br>
		    			{% endif %}

		    			{% if matchup.matchNumber >= 7 %}
		    				<br><br><br>
		    			{% endif %}

			    		{% for tournamentPlayer in matchup.playerinmatchup_set.all|dictsort:"playerNumber" %}
				    		<div class="player-box">
				    			<div class="player">
					    			{% if tournamentPlayer.isWinner %}
					    				<b>
					    			{% elif tournamentPlayer.isWinner == False %}
					    				<em>
					    			{% endif %}

				    				{{ tournamentPlayer.player.ign }}
				    				</em>
				    				</b>

					    			<input type="text" placeholder="{{ tournamentPlayer.score }}" name="Wm{{ matchup.matchNumber }}p{{ tournamentPlayer.playerNumber }}score">
				    			</div>
				    		</div>
			    		{% endfor %}

			    		{% if matchup.status == "Ongoing" %}
			    			<button type="submit" name="reportWMatch{{ matchup.matchNumber }}Score" value="reportWMatch{{ matchup.matchNumber }}Score">
			    				Report Score
			    			</button>
			    		{% else %}
			    			<br><br><br><br>
			    		{% endif %}

			    		{% if matchup.matchNumber == 4 or matchup.matchNumber >= 6 %}
			    			</div>
			    		{% endif %}
			    	{% endfor %}
			    </div>

		    {% else %}
		    	No Brackets Created Yet
		    {% endif %}

	    	{% if losersBracket %}
			    <h2>Loser's Bracket</h2>
		    	<div class="bracket">
			    	{% for matchup in losersBracket.matchups.all|dictsort:"matchNumber" %}
			    		{% if matchup.matchNumber == 1 or matchup.matchNumber == 3 or matchup.matchNumber >= 5 %}
			    			<div class="round">
			    		{% endif %}

			    		{% if matchup.matchNumber >= 5 %}
			    			<br><br><br><br>
			    		{% endif %}

			    		{% for tournamentPlayer in matchup.playerinmatchup_set.all|dictsort:"playerNumber" %}
				    		<div class="player-box">
				    			<div class="player">
					    			{% if tournamentPlayer.isWinner %}
					    				<b>
					    			{% elif tournamentPlayer.isWinner == False %}
					    				<em>
					    			{% endif %}

				    				{{ tournamentPlayer.player.ign }}
				    				</em>
				    				</b>

					    			<input type="text" placeholder="{{ tournamentPlayer.score }}" name="Lm{{ matchup.matchNumber }}p{{ tournamentPlayer.playerNumber }}score">
				    			</div>
				    		</div>
			    		{% endfor %}

			    		{% if matchup.status == "Ongoing" %}
			    			<button type="submit" name="reportLMatch{{ matchup.matchNumber }}Score" value="reportLMatch{{ matchup.matchNumber }}Score">
			    				Report Score
			    			</button>
			    		{% else %}
			    			<br><br><br><br>
			    		{% endif %}


			    		{% if matchup.matchNumber == 2 or matchup.matchNumber >= 4 %}
			    			</div>
			    		{% endif %}
			    	{% endfor %}
			    </div>

		    {% endif %}
		</form>
    </body>
{% endblock%}

laban.gg-main/labanGG/tournament_details/templates/tournament_details.html
{% extends base_template %}
{% load static %}

{% block title %}Tournament Details{% endblock %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Create Tournament</title>
        <style>
            body {
                background-color: #4D24AC; 
            }
            .black-box {
                background-color: black;
                border-radius: 30px;
                padding: 20px;
                color: white;
                margin: auto;
                width: 60%;
                margin-top: 50px;
                overflow: auto; 
            }
            .purple-box {
                background-color: #9400D3; 
                padding: 10px;
                margin-bottom: 10px;
                color: white;
            }
            .form-column {
                width: 45%;
                float: left;
                padding-right: 5%;
            }
            .header-row {
                display: flex;
                align-items: center;
                justify-content: space-between;
                margin-bottom: 20px;
            }
            h2 {
                font-size: 35px;
            }
            .pink-button {
                background-color: #F6247B;
                color: white;
                border: none;
                padding: 10px 10px;
                border-radius: 30px;
                cursor: pointer;
                margin-top: 20px;
                width: 100px;
                text-align: center;
            }


            .right-panel {
                background-color: #6549A4; 
                color: white; 
                padding: 10px; 
                width: 200px; 
                box-sizing: border-box; 
                position: fixed; 
                top: 102px; 
                right: 0; 
                bottom: 0; 
                z-index: 998; 
            }
            .right-panel button.standard {
                background-color: #CB6CE6;
                border: none;
                color: white;
                padding: 10px 100px;
                cursor: pointer;
                width: 100%;
                position: relative;
                right: 10px;
                font-size: 18px;
                display: grid;
                gap: 15px;
                grid-template-columns: auto auto;
                justify-content: center; 
                align-items: center; 
                text-align: center;
            }
            .right-panel button.pending {
                background-color: #6549A4; 
                border: none;
                cursor: pointer;
                left: 5px;
                position: relative;
                font-size: 18px;
                display: flex;
                justify-content: center; 
                align-items: center; 
                text-align: center;
            }
            .right-panel button img {
                height: 60px;
            }

        </style>
    </head>
    <body>
    <div class="black-box">
        <div class="header-row">
            <h2>Tournament Details</h2>
            <div class="pink-button"><a href="brackets/">View Brackets</a></div>
        </div>

        <!-- Display Tournament Details -->
        <div class="form-column">
            <div class="purple-box">
                <label for="id_tournament_organizer">Tournament Organizer:</label>
                <input type="text" id="id_tournament_organizer" value="{{ tournament.tournament_organizer }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_name">Name:</label>
                <input type="text" id="id_name" value="{{ tournament.name }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_game">Game:</label>
                <input type="text" id="id_game" value="{{ tournament.game }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_tier">Tier:</label>
                <input type="text" id="id_tier" value="{{ tournament.get_tier_display }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_location">Location:</label>
                <input type="text" id="id_location" value="{{ tournament.location }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_format">Format:</label>
                <input type="text" id="id_format" value="{{ tournament.get_format_display }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_application_link">Application Link:</label>
                <input type="text" id="id_application_link" value="{{ tournament.application_link }}" disabled>
            </div>
            <div class="purple-box">
                <label for="id_schedule">Schedule:</label>
                <textarea id="id_schedule" disabled>{{ tournament.schedule }}</textarea>
            </div>
            <div class="purple-box">
                <label for="id_prize_pool">Prize Pool:</label>
                <textarea id="id_prize_pool" disabled>{{ tournament.prize_pool }}</textarea>
            </div>
            <div class="purple-box">
                <label for="id_more_details">More Details:</label>
                <textarea id="id_more_details" disabled>{{ tournament.more_details }}</textarea>
            </div>
        </div>
        <!-- End of Tournament Details -->

        <!-- Right Panel -->
        <form method="POST">
            {% csrf_token %}
            <div class="right-panel">
                <h2 style='font-size:24px; width:100%; text-align: center'>
                    {% if tournament.status == "Upcoming" %}
                        Registration Open
                    {% else %}
                        Tournament {{ tournament.status }}
                    {% endif %}
                </h2>

                {% if user.isOrganizer == False %}
                    <!-- Join Tournament Button -->
                    <button class="standard" type="submit" name="goToJoinTourney" value="goToJoinTourney">
                        <b>Join Tournament</b>
                        <img src="https://clipartcraft.com/images/red-arrow-transparent-right-7.png" style='width:40px'>
                    </button>

                {% elif tournament.status != "Ended" %}
                    {% if tournament.status == "Pending" %}
                        <h2 style='color:red; font-size:24px; width:100%; text-align: center'>
                            Are you sure you want to start tournament?
                        </h2>

                        <div style='display: grid; gap: 15px; grid-template-columns: auto auto;'>
                            <button class="pending" type="submit" name="updateTourneyStatus" value="updateTourneyStatus">
                                <img src="https://cdn-icons-png.flaticon.com/512/5974/5974759.png" style='width:60px'>
                            </button>

                            <button class="pending" type="submit" name="notStartingYet" value="notStartingYet">
                                <img src="https://cdn-icons-png.flaticon.com/512/1828/1828843.png" style='width:60px'>
                            </button>
                        </div>

                    {% else %}
                        <button class="standard" type="submit" name="updateTourneyStatus" value="updateTourneyStatus">
                            <b>
                            {% if tournament.status == "Upcoming" %}
                                Start Tournament
                            {% elif tournament.status == "Ongoing" %}
                                Pause Tournament
                            {% elif tournament.status == "Paused" %}
                                Resume Tournament
                            {% endif %}
                            </b>

                            {% if tournament.status == "Upcoming" %}
                                <img src="https://clipartcraft.com/images/red-arrow-transparent-right-7.png" style='width:40px'>
                            {% elif tournament.status == "Ongoing" %}
                                <img src="https://freepngimg.com/thumb/pause_button/25377-7-pause-button-image-thumb.png" style='width:60px'>
                            {% elif tournament.status == "Paused" %}
                                <img src="https://icon-library.com/images/play-icon-png-transparent/play-icon-png-transparent-28.jpg" style='width:60px'>
                            {% endif %}
                        </button>

                    {% endif %}
                {% endif %}
            </div>
        </form>
        <!-- End of Right Panel -->
    </div>
{% endblock %}