laban.gg-main/labanGG/labanGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('games/', include('games_list.urls', namespace="games_list")),
    path('tournaments/', include('tournaments_list.urls', namespace="tournaments_list")),
    path('admin/', admin.site.urls),
    path('', include("create_tournament.urls")),
    path('log_in/', include('log_in.urls', namespace="log_in")),
    path('register/', include('register.urls', namespace="register")),
    path('tournament<int:id>/player_applications_list/', include('player_applications_list.urls', namespace="player_applications_list")),
    path('my_tournaments_organizer/', include('my_tournaments_organizer.urls', namespace="my_tournaments_organizer")),
    path('', include('join_tournament.urls', namespace="join_tournament")),
    path('notifications_page/', include('notifications_page.urls', namespace="notifications_page")),
    path('profile/', include('player_profile.urls', namespace="player_profile")),
    path('tournament<int:id>/tournament_details/', include('tournament_details.urls', namespace="tournament_details")),
    path('my_tournaments_attendee/', include('my_tournaments_attendee.urls', namespace="my_tournaments_attendee")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laban.gg-main/labanGG/log_in/urls.py
from django.urls import path
from .views import log_in_view

urlpatterns = [
    path('', log_in_view, name='log_in_view'),
    ]
# This might be needed, depending on your Django version
app_name = "log_in"

laban.gg-main/labanGG/my_tournaments_organizer/urls.py
from django.urls import path
from .views import my_tournaments_organizer, edit_tournament
from my_tournaments_organizer import views

urlpatterns = [
    path('', my_tournaments_organizer, name='my_tournaments_organizer'),
    path('edit_tournament/<int:tournament_id>/', views.edit_tournament, name='edit_tournament'),  
]

app_name = "my_tournaments_organizer"

laban.gg-main/labanGG/my_tournaments_organizer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from register.models import Account  
from create_tournament.models import Tournament
from create_tournament.forms import TournamentForm  
from django.db.models import Q  # Import Q for complex queries

def my_tournaments_organizer(request):
    user = request.user
    if user.isOrganizer:
        organizer_name = user.username
        query = request.GET.get('q')  # Get the search query from the URL parameters
        tournaments = Tournament.objects.filter(tournament_organizer=organizer_name)

        if query:
            tournaments = tournaments.filter(Q(name__icontains=query))  # Filter tournaments by name

        return render(request, 'my_tournaments_organizer.html', {'tournaments': tournaments})
    else:
        # Handle the case where the user is not a Tournament Organizer
        return redirect('/games/')

def edit_tournament(request, tournament_id):
    tournament = get_object_or_404(Tournament, id=tournament_id)
    form = TournamentForm(request.POST or None, instance=tournament)  
    if form.is_valid():
        form.save()
        return redirect('/my_tournaments_organizer/')  # Redirect to my_tournaments_organizer page after saving
    return render(request, 'edit_tournament.html', {'form': form, 'tournament': tournament})

laban.gg-main/labanGG/my_tournaments_organizer/templates/edit_tournament.html
{% extends 'base_organizer.html' %}
{% load static %}

{% block title %}My Tournaments{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <title>Create Tournament</title>
    <style>
        body {
            background-color: #4D24AC; 
        }
        .black-box {
            background-color: black;
            border-radius: 30px;
            padding: 20px;
            color: white;
            margin: auto;
            width: 60%;
            margin-top: 50px;
            overflow: auto; 
        }
        .purple-box {
            background-color: #9400D3; 
            padding: 10px;
            margin-bottom: 10px;
            color: white;
        }
        .pink-button {
            background-color: #F6247B;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 50px;
            cursor: pointer;
            float: right;
            margin-top: 20px;
        }
        .form-column {
            width: 45%;
            float: left;
            padding-right: 5%;
        }
        .header-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        h2 {
            font-size: 35px;
        }
        .upload-box {
            background-color: #B3B3B3;
            padding: 5px 10px; 
            border-radius: 10px;
            margin-right: 10px; 
        }

    </style>
</head>
<body>
    <div class="black-box">
        <h2>Edit Tournament</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-column">
                <div class="purple-box">
                    <label for="id_tournament_organizer">Tournament Organizer:</label>
                    <input type="text" id="id_tournament_organizer" value="{{ user.username }}" disabled>
                </div>
                <div class="purple-box">
                    {{ form.name.label_tag }}
                    {{ form.name }}
                </div>
                <div class="purple-box">
                    {{ form.game.label_tag }}
                    {{ form.game }}
                </div>
                <div class="purple-box">
                    {{ form.tier.label_tag }}
                    {{ form.tier }}
                </div>
                <div class="purple-box">
                    {{ form.location.label_tag }}
                    {{ form.location }}
                </div>
                <div class="purple-box">
                    {{ form.format.label_tag }}
                    {{ form.format }}
                </div>
                <div class="purple-box">
                    {{ form.application_link.label_tag }}
                    {{ form.application_link }}
                </div>
                <div class="purple-box">
                    {{ form.schedule.label_tag }}
                    {{ form.schedule }}
                </div>
            </div>
            <div class="form-column">
                <div class="purple-box">
                    {{ form.prize_pool.label_tag }}
                    {{ form.prize_pool }}
                </div>
                <div class="purple-box">
                    {{ form.more_details.label_tag }}
                    {{ form.more_details }}
                </div>
                <div class="upload-box">
                    {{ form.image.label_tag }}
                    {{ form.image }}
                </div>
            </div>
            <button type="submit" class="pink-button">Edit Tournament</button>
        </form>
    </div>
</body>
</html>
{% endblock %}

laban.gg-main/labanGG/my_tournaments_organizer/templates/my_tournaments_organizer.html
{% extends 'base_organizer.html' %}
{% load static %}

{% block title %}My Tournaments{% endblock %}

{% block content %}
<head>
    <meta charset="UTF-8">
    <style>
        body {
            background-color: #4D24AC; 
        }
        .black-box {
            background-color: black;
            border-radius: 30px;
            padding: 20px;
            color: white;
            margin: auto;
            width: 30%;
            margin-top: 50px;
            overflow: auto; 
            position: relative; 
        }
        .purple-box {
            background-color: #9400D3; 
            padding: 10px;
            margin-bottom: 10px;
            color: white;
        }
        .pink-button {
            background-color: #F6247B;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 50px;
            cursor: pointer;
            float: right;
            margin-top: 20px;
        }
        .form-column {
            width: 45%;
            float: left;
            padding-right: 5%;
        }
        .header-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
            margin-left: 680px;
        }
        h2 {
            font-size: 35px;
        }
        .upload-box {
            background-color: #B3B3B3;
            padding: 5px 10px; 
            border-radius: 10px;
            margin-right: 10px; 
        }
        .tournament-item {
            background-color: black;
            border-radius: 10px;
            padding: 10px;
            margin-bottom: 20px;
            overflow: hidden;
        }
        .tournament-image {
            float: left;
            margin-right: 10px;
            border-radius: 10px;
            overflow: hidden;
        }
        .tournament-info {
            overflow: hidden;
            margin-left: 160px;
        }
        .tournament-details {
            float: right;
            margin-top: 0;
        }
        .edit-button {
            background-color: #F6247B; 
            color: white;
            border: none;
            padding: 5px 10px;
            border-radius: 5px;
            position: absolute; 
            top: 40px; 
            right: 20px; 
            text-decoration: none; 
        }
        .pink-box {
            background-color: #F6247B;
            border-radius: 10px;
            overflow: hidden;
        }
        .icon {
            width: 20px; 
            height: 20px;
            margin-right: 5px;
            vertical-align: middle; 
        }
    </style>
</head>
<body>
    <h2 style="text-align: center; color: white;">My Tournaments</h2>
    <div class="header-row">
        <form method="GET" action="/my_tournaments_organizer/">
            <input type="text" name="q" placeholder="Search by tournament name">
            <button type="submit">Search</button>
        </form>
    </div>
    <div class="tournament-list">
        {% for tournament in tournaments %}
        <div class="black-box">
            <div class="tournament-item">
                <div class="tournament-image">
                    <div class="pink-box">
                        <img src="{{ tournament.image.url }}" alt="{{ tournament.name }} Image" style="max-width: 150px; max-height: 150px;">
                    </div>
                </div>
                <div class="tournament-info">
                    <h3>{{ tournament.name }}</h3>
                    <p>
                        <img src="https://i.gyazo.com/fb6ab2d876f03728b8409988f14b1c68.png?fbclid=IwAR0Z4PoatuWD3FgURTzOLIa17VLk3EhyC77hjD4rRqW8fwHxussBc8axpfM" alt="Calendar Icon" class="icon"> Schedule: {{ tournament.schedule }}
                    </p>
                    <p>
                        <img src="https://i.gyazo.com/ba5724c3a958c2a45f3d9cb246331803.png?fbclid=IwAR3-g3tkzxlUn9NDJG_pDqUVKiXBXY_jhYW18h1Tg4BwgDLDQ32acWjzSI8" alt="Tier Icon" class="icon"> Tier: {{ tournament.get_tier_display }}
                    </p>
                </div>
                <a href="{% url 'my_tournaments_organizer:edit_tournament' tournament.id %}" class="edit-button">Edit</a>
                <a href="/tournament{{ tournament.id }}/player_applications_list/" class="pink-button">Player Applications</a>
            </div>
        </div>
        {% empty %}
        <h3 style="text-align: center; color: red;">No Tournament Created</h3>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}