laban.gg-main/labanGG/labanGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('games/', include('games_list.urls', namespace="games_list")),
    path('tournaments/', include('tournaments_list.urls', namespace="tournaments_list")),
    path('admin/', admin.site.urls),
    path('', include("create_tournament.urls")),
    path('log_in/', include('log_in.urls', namespace="log_in")),
    path('register/', include('register.urls', namespace="register")),
    path('tournament<int:id>/player_applications_list/', include('player_applications_list.urls', namespace="player_applications_list")),
    path('my_tournaments_organizer/', include('my_tournaments_organizer.urls', namespace="my_tournaments_organizer")),
    path('', include('join_tournament.urls', namespace="join_tournament")),
    path('notifications_page/', include('notifications_page.urls', namespace="notifications_page")),
    path('profile/', include('player_profile.urls', namespace="player_profile")),
    path('tournament<int:id>/tournament_details/', include('tournament_details.urls', namespace="tournament_details")),
    path('my_tournaments_attendee/', include('my_tournaments_attendee.urls', namespace="my_tournaments_attendee")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laban.gg-main/labanGG/log_in/urls.py
from django.urls import path
from .views import log_in_view

urlpatterns = [
    path('', log_in_view, name='log_in_view'),
    ]
# This might be needed, depending on your Django version
app_name = "log_in"

laban.gg-main/labanGG/register/urls.py
from django.urls import path
from .views import register_view

urlpatterns = [
    path('', register_view, name='register_view'),
]
# This might be needed, depending on your Django version
app_name = "register"

laban.gg-main/labanGG/register/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse

# Create your models here.

def validate_contact_number(value):
    """
    Validate that the mobile number has the format #### ### ###
    """
    if len(value.replace(' ', '')) != 11 or not value.replace(' ', '').isdigit():
        raise ValidationError('Mobile number must be in the format #### ### ####')

class Account(models.Model):
    username = models.CharField(max_length=32)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=32)
    isOrganizer = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    last_login = models.DateTimeField(blank=True, null=True)

    def __str__(self) -> str:
        return f"{self.username}, {self.email}"
    
    def get_username(self):
        return self.email

    def has_module_perms(self, register):
        return self.is_staff
    
    def get_absolute_url(self):
        return reverse('player_profile:player-detail', kwargs={'pk':self.pk})

class OrganizerAccount(Account):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=32)
    contact_number = models.CharField(max_length=15, validators=[validate_contact_number])
    past_experience = models.TextField(blank = True, null = True)
    additional_comments = models.TextField(blank = True, null = True)

    def __str__(self) -> str:
        return f"{self.username}, {self.email}"
    
    def save(self, *args, **kwargs):
        self.isOrganizer = True
        super().save(*args, **kwargs)

laban.gg-main/labanGG/register/forms.py
from django import forms

from .models import Account, OrganizerAccount

class AccountForm(forms.ModelForm):
    confirm_email = forms.EmailField(max_length=100)
    confirm_password = forms.CharField(max_length=32)
    class Meta:
        model = Account
        fields = ['username', 'email', 'password']

    def clean(self):
        cleaned_data = super(AccountForm, self).clean()
        email = cleaned_data.get("email")
        confirm_email = cleaned_data.get("confirm_email")
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if email != confirm_email:
            self.add_error('confirm_email', "Email does not match")

        if password != confirm_password:
            self.add_error('confirm_password', "Password does not match")

        return cleaned_data
    
class OrganizerAccountForm(forms.ModelForm):
    confirm_email = forms.EmailField(max_length=100)
    confirm_password = forms.CharField(max_length=32)
    class Meta:
        model = OrganizerAccount
        fields = ['username', 'email', 'password', 'first_name', 'last_name', 'contact_number', 'past_experience', 'additional_comments']

        def clean(self):
            cleaned_data = super(AccountForm, self).clean()
            email = cleaned_data.get("email")
            confirm_email = cleaned_data.get("confirm_email")
            password = cleaned_data.get("password")
            confirm_password = cleaned_data.get("confirm_password")

            if email != confirm_email:
                self.add_error('confirm_email', "Email does not match")

            if password != confirm_password:
                self.add_error('confirm_password', "Password does not match")

            return cleaned_data


    
        

laban.gg-main/labanGG/register/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse

from .forms import AccountForm, OrganizerAccountForm
from .models import Account

# Create your views here.
# def index(request):
#     return HttpResponse('Hello World! This came from the index view')


def register_view(request):
    if request.method == 'POST':
        if 'form1_submit' in request.POST:
            form1 = AccountForm(request.POST)
            form2 = OrganizerAccountForm()
            if form1.is_valid():
                form1.save()
                return redirect('/log_in/')
        elif 'form2_submit' in request.POST:
            form2 = OrganizerAccountForm(request.POST)
            form1 = AccountForm()
            if form2.is_valid():
                form2.save()
                return redirect('/log_in/')
    else:
        form1 = AccountForm()
        form2 = OrganizerAccountForm()
    return render(request, 'register/register.html', {'form1': form1, 'form2': form2})

laban.gg-main/labanGG/register/templates/register/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Account</title>
    <style>
        body {
            background-color: #4D24AC; 
        }
        .black-box {
            background-color: black;
            border-radius: 30px;
            padding: 20px;
            color: white;
            margin: auto;
            width: 60%;
            margin-top: 50px;
            overflow: auto; 
        }
        .purple-box {
            background-color: #9400D3; 
            padding: 10px;
            margin-bottom: 10px;
            color: white;
        }
        .pink-button {
            background-color: #F6247B;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 50px;
            cursor: pointer;
            float: right;
        }
        .form-column {
            width: 45%;
            float: left;
            padding-right: 5%;
        }
        .header-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            margin-bottom: 20px;
        }
        h2 {
            font-size: 35px;
        }
        .upload-container {
            display: flex;
            align-items: center;
        }
        .upload-box {
            background-color: #B3B3B3;
            padding: 5px 10px; 
            border-radius: 10px;
            margin-right: 10px; 
        }
        .upload-text {
            color: white;
        }
        .upload-button {
            background-color: #B3B3B3;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 10px;
            cursor: pointer;
        }
        .underline-button {
            color: inherit;
            text-decoration: none;
            border: none;
            background-color: transparent;
            cursor: pointer;
            outline: none;
            border-bottom: 1px solid;
            padding: 0;
        }


        /* Styling for the option buttons */
        .option-button {
            cursor: pointer;
            padding: 5px 10px;
            margin-right: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
        }

        /* Styling for the active option button */
        .option-button.active {
            background-color: #ddd;
        }

          /* Styling for the forms */
        .form-container {
            display: none; /* Hide forms by default */
        }

        /* Styling for the active form */
        .form-container.active {
            display: block; /* Show active form */
        }
    </style>
</head>

<body>
    <div class="black-box">
        <div class="header-row">
            <h2>Register Account</h2>
            <div>
                <button class=underline-button id="goToLoginPage">Already have an account? Log in</button>
            </div>
            <div class="option-button active" onclick="showForm('form1')">Tournament Attendee</div>
            <div class="option-button" onclick="showForm('form2')">Tournament Organizer</div>
        </div>

        <form id="form1" class="form-container active" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-column">
                <div class="purple-box">
                    <label for="username">Username</label><br>
                    <input type="text" name="username" id="username" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="email">Email</label><br>
                    <input type="text" name="email" id="email" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="password">Password</label><br>
                    <input type="text" name="password" id="password" class="purple-box" required="True">
                </div>
                {% block content %}
                    {{ form1.non_field_errors }}
                    {% for field in form1 %}
                        {% if field.errors %}
                            <p>{{ field.label }} has the following errors:</p>
                            <ul>
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endblock %}
            </div>
            <div class="form-column">
                <div class="purple-box">
                    <label for="confirm_email">Confirm Email</label><br>
                    <input type="text" name="confirm_email" id="confirm_email" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="confirm_password">Confirm Password</label><br>
                    <input type="text" name="confirm_password" id="confirm_password" class="purple-box" required="True">
                </div>
            </div>
            <button type="submit" class="pink-button" name="form1_submit">Register</button>
        </form>

        <form id="form2" class="form-container" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-column">
                <div class="purple-box">
                    <label for="username">Username</label><br>
                    <input type="text" name="username" id="username" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="email">Email</label><br>
                    <input type="text" name="email" id="email" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="password">Password</label><br>
                    <input type="text" name="password" id="password" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="confirm_email">Confirm Email</label><br>
                    <input type="text" name="confirm_email" id="confirm_email" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="confirm_password">Confirm Password</label><br>
                    <input type="text" name="confirm_password" id="confirm_password" class="purple-box" required="True">
                </div>
                {% block content2 %}
                    {{ form2.non_field_errors }}
                    {% for field in form2 %}
                        {% if field.errors %}
                            <p>{{ field.label }} has the following errors:</p>
                            <ul>
                            {% for error in field.errors %}
                            <li>{{ error }}</li>
                            {% endfor %}
                            </ul>
                        {% endif %}
                    {% endfor %}
                {% endblock %}
            </div>

            <div class="form-column">
                <div class="purple-box">
                    <label for="first_name">First Name</label><br>
                    <input type="text" name="first_name" id="first_name" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="last_name">Last Name</label><br>
                    <input type="text" name="last_name" id="last_name" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="contact_number">Contact Number</label><br>
                    <input type="text" name="contact_number" id="contact_number" class="purple-box" required="True">
                </div>
                <div class="purple-box">
                    <label for="past_experience">Past Experience</label><br>
                    <textarea name="past_experience" id="past_experience" rows="6" class="purple-box"></textarea>
                </div>
                <div class="purple-box">
                    <label for="additional_comments">Additional Comments</label><br>
                    <textarea name="additional_comments" id="additional_comments" rows="6" class="purple-box"></textarea>
                </div>
            </div>
            <button type="submit" class="pink-button" name="form2_submit">Register</button>
        </form>

        
    </div>

    <script>
        function showForm(formId) {
          // Hide all form containers
          var formContainers = document.getElementsByClassName("form-container");
          for (var i = 0; i < formContainers.length; i++) {
            formContainers[i].classList.remove("active");
          }
          
          // Show the selected form container
          var selectedForm = document.getElementById(formId);
          selectedForm.classList.add("active");
        
          // Update the active state of option buttons
          var optionButtons = document.getElementsByClassName("option-button");
          for (var i = 0; i < optionButtons.length; i++) {
            optionButtons[i].classList.remove("active");
            if (optionButtons[i].getAttribute("onclick").includes(formId)) {
              optionButtons[i].classList.add("active");
            }
          }
        }
        document.getElementById("goToLoginPage").addEventListener("click", function() {
            window.location.href = "{% url 'log_in:log_in_view' %}";
        });
        </script>

</body>
</html>