laban.gg-main/labanGG/games_list/urls.py
from django.urls import path
from .views import GamesListView, GamesDetailView, GamesSearchView

urlpatterns = [
    path('', GamesListView.as_view(), name='index'),
    path('<int:pk>/', GamesDetailView.as_view(), name='games-detail'),
    path('search-games/', GamesSearchView.as_view(), name='games-search'),

]
# This might be needed, depending on your Django version
app_name = "games_list"

laban.gg-main/labanGG/labanGG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path('games/', include('games_list.urls', namespace="games_list")),
    path('tournaments/', include('tournaments_list.urls', namespace="tournaments_list")),
    path('admin/', admin.site.urls),
    path('', include("create_tournament.urls")),
    path('log_in/', include('log_in.urls', namespace="log_in")),
    path('register/', include('register.urls', namespace="register")),
    path('tournament<int:id>/player_applications_list/', include('player_applications_list.urls', namespace="player_applications_list")),
    path('my_tournaments_organizer/', include('my_tournaments_organizer.urls', namespace="my_tournaments_organizer")),
    path('', include('join_tournament.urls', namespace="join_tournament")),
    path('notifications_page/', include('notifications_page.urls', namespace="notifications_page")),
    path('profile/', include('player_profile.urls', namespace="player_profile")),
    path('tournament<int:id>/tournament_details/', include('tournament_details.urls', namespace="tournament_details")),
    path('my_tournaments_attendee/', include('my_tournaments_attendee.urls', namespace="my_tournaments_attendee")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

laban.gg-main/labanGG/log_in/urls.py
from django.urls import path
from .views import log_in_view

urlpatterns = [
    path('', log_in_view, name='log_in_view'),
    ]
# This might be needed, depending on your Django version
app_name = "log_in"

laban.gg-main/labanGG/register/urls.py
from django.urls import path
from .views import register_view

urlpatterns = [
    path('', register_view, name='register_view'),
]
# This might be needed, depending on your Django version
app_name = "register"

laban.gg-main/labanGG/log_in/models.py
from django.db import models

# Create your models here.

laban.gg-main/labanGG/log_in/forms.py
from django import forms

from register.models import Account

class LogInForm(forms.Form):
    email_username = forms.CharField(max_length=100, label="Email or username")
    password = forms.CharField(max_length=32)

    def clean(self):
        cleaned_data = super(LogInForm, self).clean()
        email_username = cleaned_data.get("email_username")
        password = cleaned_data.get("password")

        if Account.objects.filter(username=email_username).exists():
           if Account.objects.filter(password=password).exists():
              pass
           else:
               self.add_error('password', "Password is incorrect")
        elif Account.objects.filter(email=email_username).exists():
            if Account.objects.filter(password=password).exists():
              pass
            else:
               self.add_error('password', "Password is incorrect")
        else:
           self.add_error('email_username', "Email or username does not exist ")

        return cleaned_data

laban.gg-main/labanGG/log_in/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout

from .forms import LogInForm
# Create your views here.

def log_in_view(request):
    user = request.user
    if (user):
        logout(request)

    if request.method == 'POST':
        if 'form_submit' in request.POST:
            form = LogInForm(request.POST)
            if form.is_valid():
                email_username = form.cleaned_data['email_username']
                password = form.cleaned_data['password']
                user = authenticate(request, username=email_username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('/games/')
    else:
        form = LogInForm()
    return render(request, 'log_in/log_in.html', {'form': form})

laban.gg-main/labanGG/log_in/templates/log_in/log_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log In Account</title>
    <style>
        body {
            background-color: #4D24AC; 
        }
        .black-box {
            background-color: black;
            border-radius: 30px;
            padding: 20px;
            color: white;
            margin: auto;
            width: 60%;
            margin-top: 50px;
            overflow: auto;
            text-align: center;
        }
        .purple-box {
            background-color: #9400D3; 
            display: grid;
            place-items: center;
            padding: 20px;
            margin: 0 auto;
            align-items: center;
            justify-content: center;
            width: 25%;
            color: white;
            margin-top: -20px;
        }
        .purple-box-input {
            background-color: #9400D3; 
            padding: 10px;
            align-items: center;
            justify-content: center;
            text-align: center;
            width: 100%;
            color: white;
        }
        .pink-button {
            background-color: #F6247B;
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 50px;
            cursor: pointer;
            float: right;
        }
        .form-column {
            width: 45%;
            float: left;
            padding-right: 5%;
        }
        .header-row {
            display: flex;
            align-items: center;
            justify-content: center;
        }
        h2 {
            font-size: 35px;
        }
        .underline-button {
            color: inherit;
            text-decoration: none;
            border: none;
            background-color: transparent;
            cursor: pointer;
            outline: none;
            border-bottom: 1px solid;
            padding: 0;
            margin-bottom: 40px;
        }
        .log-in-as-guest-button {
            position: fixed;
            bottom: 20px; /* Adjust as needed */
            right: 20px; /* Adjust as needed */
            color: inherit;
            text-decoration: none;
            border: none;
            background-color: transparent;
            cursor: pointer;
            outline: none;
            border-bottom: 1px solid;
            padding: 0;
        }
    </style>
</head>

<body>
    <div class="black-box">
        <div class="header-row">
            <h2>Log In Account</h2>
        </div>

        <div>
            <button class=underline-button id="goToRegisterPage">Don't have an account? Sign up for free</button>
        </div>

        <form id="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="purple-box">
                    <label for="email_username">Email or Username</label><br>
                    <input type="text" name="email_username" id="email_username" class="purple-box-input" required="True">
                </div>
                <div class="purple-box">
                    <label for="password">Password</label><br>
                    <input type="text" name="password" id="password" class="purple-box-input" required="True">
                </div>
                {% block content %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        {% if field.errors %}
                            <p>{{ field.label }} has the following errors:</p>
                            {% for error in field.errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endblock %}
            <button type="submit" class="pink-button" name="form_submit">Log In</button>
        </form>

        <button class="log-in-as-guest-button" id="goToGamesPageAsGuest">Log In as Guest</button>

        <script>
            document.getElementById("goToRegisterPage").addEventListener("click", function() {
                window.location.href = "{% url 'register:register_view' %}";
            });
            document.getElementById("goToGamesPageAsGuest").addEventListener("click", function() {
                window.location.href = "{% url 'games_list:index' %}";
            });
        </script>

</body>
</html>